# Generated by Django 4.1.7 on 2023-03-24 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_blog_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Employee',
        ),
    ]
