# Generated by Django 4.1.7 on 2023-03-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Backend', '0003_rename_blog_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='author_description',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='author_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='title',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='content',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='cover_img',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='slug',
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
