# Generated by Django 4.1.7 on 2023-03-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_rename_author_description_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
