# Generated by Django 4.1.7 on 2023-03-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_employee_is_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.TextField(unique=True),
        ),
    ]
